# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish snapshot Docker images of Astarte tools

on:
  push:
    paths:
    - 'tools/**'
    - '.github/workflows/publish-tool-snapshot-to-dockerhub-workflow.yaml'
    branches:
    - 'master'
    - 'release-*'

jobs:
  push_tool_snapshot_to_registry:
    name: Push Docker images of Astarte tools to Docker Hub
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        app:
        - astarte_device_fleet_simulator
        - astarte_e2e
        - astarte_export
        - astarte_import
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get current datetime
        id: datetime
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compute tag name for snapshot images of Astarte tools
        id: compute-tag
        run: |
          export TAG="$(echo ${{ github.ref }} | sed 's,refs/heads/,,' | sed 's/master/snapshot/g' | sed 's/release-\(.*\)/\1-snapshot/g' )"
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels) of Astarte tools for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            astarte/${{ matrix.app }}
          tags: |
            # TODO we probably want something smarter, but the 'pattern' type runs only on tags at the moment
            type=raw,value=${{ steps.compute-tag.outputs.TAG }}
          labels: |
            org.opencontainers.image.created=${{ steps.datetime.outputs.BUILD_DATE }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and push tagged Docker image of Astarte tools
        id: push
        uses: docker/build-push-action@v6.18.0
        with:
          context: tools/${{ matrix.app }}
          file: tools/${{ matrix.app }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.labels }}
